import Head from 'next/head';

export default function Home() {
    return (
        <div className={'container mx-auto'}>
            <Head>
                <title>Micro Web</title>
                <meta name='description' content='Generated by Micro Web' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                <h1 className={'font-bold'}>Halaman Utama</h1>
            </main>
        </div>
    );
}
