import Head from 'next/head';

import CircleSvg from 'src/pages/components/svg/circle';

import Header from 'src/parts/Header';
import Hero from 'src/parts/Hero';
import Clinets from 'src/parts/Clients';
import ListCourses from 'src/parts/ListCourses';
import ListCategories from 'src/parts/ListCategories';
import Footer from 'src/parts/Footer';

import coursesApi from 'src/constants/api/courses';
function Home({ data }) {
    return (
        <>
            <Head>
                <title>Micro Web</title>
                <meta name='description' content='Generated by Micro Web' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                <section className={'header-clipping pt-10'}>
                    <CircleSvg className={'absolute bottom-0 left-0'} />
                    <div className={'sunshine'}></div>
                    <div className='container mx-auto'>
                        <Header></Header>
                        <Hero></Hero>
                    </div>
                </section>
                <section className={'container mx-auto pt-24'}>
                    <Clinets></Clinets>
                </section>
                <section className={'container mx-auto pt-24'}>
                    <ListCourses data={data}></ListCourses>
                </section>
                <section className={'container mx-auto pt-24'}>
                    <ListCategories></ListCategories>
                </section>
                <section className={'mt-24 bg-indigo-1000 py-12'}>
                    <Footer></Footer>
                </section>
            </main>
        </>
    );
}

Home.getInitialProps = async () => {
    try {
        const data = await coursesApi.all();
        return { data: data.data };
    } catch (error) {
        return { error };
    }
};

export default Home;
